#PBS -N matsumura2_5
#PBS -l nodes=1:ppn=10
#PBS -l mem=2GB
#PBS -l file=100MB
#PBS -M hvu@colgate.edu
#PBS -q biomath
#PBS -j oe
#PBS -o output.pbs-job2_5
#PBS -l walltime=360:00:00
cd $PBS_O_WORKDIR

time mpirun -np 5 ~/Matsumura/sres/sres -p 20 -r ~/Matsumura/sres/ayRanges.txt -f ~/Matsumura/simulation/simulation -t ~/Matsumura/sres/output/g0h18m2p108_2_5.txt -G 0.8 -a -S 0.005 -g 20 --quiet > matsumura2_5_scn_ocl.txt

